version: "3.9"
services:
  devopsdb:
    image: ganeshdhanala/automation:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 3
    networks:
      - mynetwork

  application:
    image: ganeshdhanala/automation:myappiamge
    ports:
      - "6666:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
